ANDROID: Fix missing header file for get_cmdline() call
commit ab6f11cf39b6a605b0e644ac1fde21d517d56d40
    uid_sys_stats: log task io with a debug flag
causes on some builds next error:
error: implicit declaration of function 'get_cmdline'
    [-Werror=implicit-function-declaration]

[mikeioannina]: Reapply patch after wrong CAF conflict resolution
Change-Id: I41adaf5af999b94bac41e3f17a67cfc88400ee31
Signed-off-by: Dmitry Shmidt <dimitrysh@google.com>